baseurl: https://telaroz.netlify.app/
theme: hugo-nederburg-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
preserveTaxonomyNames: yes
paginate: 5
defaultContentLanguage: en
defaultContentLanguageInSubdir: no
privacy:
  googleAnalytics:
    anonymizeIP: no
    disable: no
    respectDoNotTrack: no
    useSessionStorage: no
languages:
  en:
    title: Handball and Data
    contentDir: content/en
    params:
      author: Valery Zúñiga
      authorLink: https://telaroz.netlify.app/
      copyright:
      description: Handball and #rstats
      email: telaroz@gmail.com
      slogan: 
      social:
        email: telaroz@gmail.com
        github: https://github.com/telaroz/
        stackoverflow: https://stackoverflow.com/users/9905964/telaroz
        twitter: https://twitter.com/telaroz/
      writers:
        Valery Zúñiga:
          bio: Handball player and data analyst
          email: telaroz@gmail.comom
          github: https://github.com/telaroz/
          link: https://telaroz.netlify.app/
          stackoverflow: https://stackoverflow.com/users/9905964/telaroz
          twitter:  https://twitter.com/telaroz/
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: about/
          weight: 2
        - name: Get in touch
          url: contact/
          weight: 3
    weight: 1
  sp:
    title: Balonmano y Datos
    contentDir: content/sp
    params:
      author: Valery Zúñiga
      title: Handball and Data
      authorLink: https://telaroz.netlify.app/
      copyright:
      description: Handball and #rstats
      email: telaroz@gmail.com
      slogan: 
      social:
        email: telaroz@gmail.com
        github: https://github.com/telaroz/
        stackoverflow: https://stackoverflow.com/users/9905964/telaroz
        twitter: https://twitter.com/telaroz/
      writers:
        Valery Zúñiga:
          bio: Handball player and data analyst
          email: telaroz@gmail.comom
          github: https://github.com/telaroz/
          link: https://telaroz.netlify.app/
          stackoverflow: https://stackoverflow.com/users/9905964/telaroz
          twitter:  https://twitter.com/telaroz/
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: About
          url: about/
          weight: 2
        - name: Get in touch
          url: contact/
          weight: 3
    weight: 2